### ISSUE TITLE
Specify page to play music

### ISSUE THREAD

**Issue by sonderlau** [PentaTea/B-Tree.studio#4]
在指定的页面显示该控件
可以考虑设置白名单或者黑名单的形式

**Comment by PentaTea** [comment]
好.这两天考虑添加

**Comment by PentaTea** [comment]
@sonderlau  请问你可以描述一下在生产环境中的实际应用场景吗
我在考虑需不需要储存当前音乐进度,需不需要声音渐隐之类的操作

**Comment by sonderlau** [comment]
> @sonderlau 请问你可以描述一下在生产环境中的实际应用场景吗
> 我在考虑需不需要储存当前音乐进度,需不需要声音渐隐之类的操作

我自己使用的话 是在一个给同学们提供笔记在线阅读的地方
我个人觉得在阅读文字的时候显示一个音乐播放器有点不那么严肃
但是在关于页面 还有节假日或者学校的特殊日子的时候 会有活动页面 如果有音乐之类的衬托一下气氛就特别棒了

至于你刚刚提到的几个建议 我是这么想的：
- 存储音乐进度 
	- 我目前还不是很用得到 不过我猜测 也许可以设置某个目录下的所有页面使用同一个存储进度 因为存在使用场景是那种目录分支特别多的情况
- 声音渐隐 
	- 可以添加一个option 在点击暂停的时候 是立即停止还是逐渐停止 
	- 同样的 也可以设置转到特定设置页面的时候 比方说从活动页面到文档阅读页面时 对声音暂停或者渐隐操作

我自己也是一个刚入门前端的萌新 然后也是第一次提需求 😆 
不成熟的地方 还望多多交流
以上

**Comment by PentaTea** [comment]
@sonderlau 当时写这个东西的时候我还挺菜,现在加功能这代码差点没搞死我.
我抽空实现一个仅可以设定路径的小版本,后续会重构一次代码实现读取不同页面的配置信息

**Comment by cpkang** [comment]
请问为什么添加插件 添加音乐后 没变化呢
